#!/bin/bash

# Helper functions {{{

_check_exists_rsync_arg() {
# Returns 0 if the argument exists already as an option, returns 1 otherwise
    arg="$1"
    check="$(echo "$SYNC" | grep "$arg")"
    exists="$?"
    return "$exists"
}

_add_rsync_arg() {
    arg="$1"
    # If the rsync arg exists, then dont do anything, else remove it.
    if [ _check_exists_rsync_arg "$arg" == 0 ]; then
        continue
    else
        SYNC="$SYNC --$arg"
    fi
}

_remove_rsync_arg() {
    arg="$1"
    # If the rsync arg exists, then remove it, else don't do anything.
    if [ _check_exists_rsync_arg "$arg" == 0 ]; then
        SYNC=$(echo "$SYNC" | sed "s/ --$arg//g")
    else
        continue
    fi
}
# }}}

# Config Section {{{

config_file="$HOME/.config/zinc/zinc.conf"

if [ ! -f "$config_file" ]; then
    echo "Config file not found at $config_file."
    read -p "Would you like to create the default config file at $config_file [y/N]?: " option
    case "$option" in
        [Yy]*)
            cat << CONFIG_END > "$config_file"
server="username@server.com"
local_folder="~/Study"
remote_folder="~/Study"
file_permissions_available="true"
default_direction="bidirectional"
colorize="true"
CONFIG_END
            echo "Created the default config file at $config_file."
            ;;
        *)
            exit
            ;;
    esac
fi

source "$config_file"

# }}}

# Variables {{{
hello() {
default_direction="$1"
}
echo "$default_direction"
# }}}
