alias s="zathura --fork"
alias p="python"
alias t="todo.sh -d ~/.config/todo/todo.cfg"
alias vrc="nvim ~/.vimrc"
alias irc="nvim ~/.config/i3/config"
alias tw="tiddlywiki"
alias hp="nvim ~/Online/Startpage/index.html"
