set nocompatible
let g:bundle_path = '~/.vim/bundle'

call plug#begin(bundle_path)
Plug 'lervag/vimtex'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'tpope/vim-fugitive'
Plug 'itchyny/lightline.vim'
Plug 'sirver/ultisnips'
Plug 'altercation/vim-colors-solarized'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-surround'
Plug 'spinks/vim-leader-guide'
Plug 'scrooloose/nerdcommenter'
Plug 'godlygeek/tabular'
Plug 'Konfekt/FastFold'
Plug 'dylanaraps/wal.vim'
Plug 'tmhedberg/SimpylFold'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-lua/plenary.nvim'
Plug 'JuliaEditorSupport/julia-vim'
call plug#end()

let g:config_root = fnamemodify(resolve(expand('<sfile>:p')), ':h')

let g:config_file_list = [
            \'options.vim',
            \'autocommands.vim',
            \'ui.vim',
            \'keys.vim'
            \]

for s:fname in g:config_file_list
    execute printf('source %s/core/%s', g:config_root, s:fname)
endfor

let g:config_plugin_list = [
            \'coc.vim',
            \'vimtex.vim',
            \'goyo.vim',
            \'ultisnips.vim',
            \'rainbowparentheses.vim',
            \'nerdcommenter.vim'
            \]

for s:fname in g:config_plugin_list
    execute printf('source %s/config/%s', g:config_root, s:fname)
endfor
